### PR TITLE
Update README.md

### LINKED ISSUE #1: coverage reporting is missing
Let's add coverage reporting, as it's done for example in `eo-files` repo. Check the `codecov.yml` file they have in GitHub Actions. Also, don't forget to add the badge to README.

### PR DESCRIPTION
**Pull request by kerelape**
Add code coverage badge
Fix #1

### CODE REVIEW

**Comment by kerelape** [comment]
@rultor merge

**Comment by kerelape** [comment]
@yegor256 Looks like rultor is not added to this repository as a collaborator

**Comment by yegor256** [comment]
@kerelape I just added him

**Comment by yegor256** [comment]
@kerelape most probably it won't work because your default branch is `main`. I will change it now to `master`

**Pull request closed without merging**
