### PR TITLE
Replaced junit meta

### PR DESCRIPTION
**Pull request by Graur**
Closes: #24

- updated EO version;
- replaced junit meta
- fixed some syntax mistakes

---

## PR-Codex overview
This PR adds and updates packages and dependencies for the EO Programming Language's `org.eolang.net` project. 

### Detailed summary
- Adds `tests` package to `src/test/eo/org/eolang/net/socket-tests.eo`
- Adds `home`, `package`, and `version` properties to `src/main/eo/org/eolang/net/socket.eo`
- Updates `org.eolang:eo-runtime` dependency to version `0.29.5`
- Adds `org.junit.jupiter:junit-jupiter-params` dependency for testing
- Adds license header to package-info.java files
- Updates `com.jcabi:parent` dependency to version `0.65.0`
- Adds `stack-size` property to `pom.xml` for `maven-surefire-plugin` configuration
- Updates `org.eolang:eo-maven-plugin` dependency to version `0.29.5`
- Excludes `duplicatefinder` from `qulice-maven-plugin` configuration

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by yegor256** [comment]
@Graur some checks are broken :(

**Comment by Graur** [comment]
@yegor256 I fixed these checks. I uodated `EOsocket.java` file and removed dependency from `txt` package. Since we lost this package in runtime and I can't figure out why did this happen. Can you please have a look?

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by Graur** [comment]
@yegor256 Can you help to merge it again, please?

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by Graur** [comment]
@yegor256 I get it. Looks like we need to merge it manually. Since `.rultor.yml` would be updated after merging corresponding changes. I will create a new pull request with changes only in `.rultor.yml`

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
